### ISSUE TITLE
Arabidopsis 1001G data in MatrixTubemap

### ISSUE THREAD

**Issue by josiahseaman** [graph-genome/MatrixTubeMap#13]
- [x] Identify data source: six_ref.GFA
- [x] Install / Compile ODGI 
- [x] Process through ODGI
- [x] Process through Tubeify
- [x] Import into tubemap.js
- [x] Rendered and browsing (performant)
- [ ] Links verified correct
- [x] reasonable size 5 MB (larger binning for whole?)
- [x] Sebastian's data converted
- [ ] Sebastian's data visualized

**Comment by ekg** [comment]
Here's how to take a GFA file and make the tubmap bin input:

```
odgi build -g x.gfa -o - | odgi sort -i - -o x.og
odgi bin -i x.og -w $bin_width -j | gzip >x.og.$bin_width.json.gz
```

**Comment by josiahseaman** [comment]
Actual commands used:
```
cmake -H. -Bbuild && cmake --build build -- -j 3

./odgi build -g sixref_Chr4.gfa -o - | ./odgi sort -i - -o sixref_Chr4.og
bin_width=100000
./odgi bin -i sixref_Chr4.og -w $bin_width -j > sixref_Chr4.og.$bin_width.json.gz
bin_width=10000
./odgi bin -i sixref_Chr4.og -w $bin_width -j  >sixref_Chr4.og.$bin_width.json
bin_width=1000
./odgi bin -i sixref_Chr4.og -w $bin_width -j > sixref_Chr4.og.$bin_width.json
bin_width=100
./odgi bin -i sixref_Chr4.og -w $bin_width -j > sixref_Chr4.og.$bin_width.json

node.exe cli.js -j data\sixref_Chr4.og.10000.json --bin_length=10000 --tiles=1 --tile_json=data\sixref_Chr4.og.10000.tile.json
node.exe cli.js -j data\sixref_Chr4.og.1000.json --bin_length=1000 --tiles=1 --tile_json=data\sixref_Chr4.og.1000.tile.json
node.exe cli.js -j data\sixref_Chr4.og.100.json --bin_length=100 --tiles=1 --tile_json=data\sixref_Chr4.og.100.tile.json
```

**Comment by josiahseaman** [comment]
![image](https://user-images.githubusercontent.com/2256148/65886465-48f21380-e394-11e9-9803-aa3838fcfdab.png)
Real Arabidopsis data is working!  I will definitely need #14 for this data, because it's very detailed and doesn't all fit into view easily.  

![image](https://user-images.githubusercontent.com/2256148/65887833-7fc92900-e396-11e9-83a3-0e7ce7fc49b2.png)
Bin size = 100. `translate(0,0) scale(0.0038, 2)`

![image](https://user-images.githubusercontent.com/2256148/65886972-30362d80-e395-11e9-9666-9035635bbec5.png)
This is the entire Chr4 bins at bin size 1k. `transform="translate(0,0) scale(0.038,1.9)"`

![image](https://user-images.githubusercontent.com/2256148/65887461-dda94100-e395-11e9-965a-cb35984c4a4a.png)
Bin size 10k.

![image](https://user-images.githubusercontent.com/2256148/65886624-9a020780-e394-11e9-99b8-adc5f6228030.png)
Interestingly, file size between the formats doesn't scale linearly.  This tells me that at small bin sizes, (100.json)  there are long runs of contiguous ids covered.

**Comment by josiahseaman** [comment]
Currently waiting on Sebastian for more data.
